# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               'GalSagie'
name:                'Gal Sagie Blog'
tagline:             'A blog about network virtualization and cloud'
description:         'My blog about everything related to SDN, NFV, Virtualization and Cloud'
url:                 http://galsagie.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gal Sagie
  url:               https://galsagie.github.io
  email:             gal.sagie@gmail.com

# Custom vars
version:             1.0.0
